SM-Dev/src/objects/Seeddata_Acc_Seq_Data__c.object
<CustomObject>
    <description>This object holds the Account sequence Name and Account Sequence Data values structure of the Seed data provided by SAP.</description>
    <fields>
        <fullName>AccountSequenceData__c</fullName>
        <description>Account sequence data : This fields holds the Account sequence data value of the Account sequence data derived from the SAP seed data.</description>
        <label>Account Sequence Data</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountSequenceName__c</fullName>
        <description>Account sequence name : This fields holds the account sequence name of the Account sequence data derived from the SAP seed data.</description>
        <label>Account Sequence Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Seeddata_Acc_Seq_Data</label>
    <nameField>
        <displayFormat>SEQD-{0000}</displayFormat>
        <label>Account Sequence Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seeddata_Acc_Seq_Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SM-Dev/src/objects/Seeddata_Acc_Seq_fields__c.object
<CustomObject>
    <description>FIELD to account sequence : This object accommodates the field to account sequence mapping, which is derived from the SAP seed data service. This mapping is used to identify the dependency field values in the service.</description>
    <fields>
        <fullName>AccountSequenceDescription__c</fullName>
        <description>Account Sequence Description : This field accommodates the actual sequence description which tells us where to look into for the dependent field information. This data is derived from the SAP seed data.</description>
        <label>Account Sequence Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountSequenceName__c</fullName>
        <description>Account sequence name : This field accommodates the Account sequence name, which tells us the sequence Name to look into for the required information. This values is derived from the SAP system.</description>
        <label>Account Sequence Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KEYFIELDNAME__c</fullName>
        <description>KEY FIELD NAME : This Field accommodates the Values of the field we are looking for in the mapping structure. This data is derived from the SAP seed data service.</description>
        <label>KEY FIELD NAME</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Seeddata_Acc_Seq_Fields</label>
    <nameField>
        <displayFormat>SEQF-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seeddata_Acc_Seq_Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SM-Dev/src/objects/SeeddataKeyValues__c.object
<CustomObject>
    <description>Seeddata Key Values : This object accommodates the actually information and the description for individual seed data information. Actually raw data format.</description>
    <fields>
        <fullName>FieldDescription__c</fullName>
        <description>Field Description : This field accommodates the data description for the individual seed data values derived from the service.</description>
        <label>Field Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>FIELD NAME : This Field accommodates the Seed data type for the Raw data, this information is derived from the SAP system.</description>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldValue__c</fullName>
        <description>FIELD VALUE : This field accommodates the value of the individual seed data item. This is derived from the SAP seed data information.</description>
        <label>Field Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Seeddata_Key_Values</label>
    <nameField>
        <displayFormat>SDKEYVAL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seeddata_Key_values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SM-Dev/src/classes/SeedDataProcessorBatch.cls
global class SeedDataProcessorBatch implements Database.Batchable<string>, Database.Stateful, Database.AllowsCallouts  {
//global boolean bReRun = false; //will be used to determine if batch has to re-run in case there are more that 10K of records
global Iterable<string> start(Database.BatchableContext ctx) {
    return new list<String> { 'Seeddata_Acc_Seq_Data__c','Seeddata_Acc_Seq_fields__c','SeeddataKeyValues__c'}; //list of strings with my object names
}
global void execute(Database.BatchableContext ctx, list<string> lstsObjectName) {
    list<sObject> lstDeleteRecords = new list<sObject>();
    list<sObject> insertRecords = new list<sObject>();
    String JsonResponse = CommonServiceApiUtil.sendApiRequest('callout:SAP_SEED_DATA','', 'GET');
    system.debug(JsonResponse);
    if(JsonResponse != null && JsonResponse!='')
    {
        datetime dt = System.now();
    	system.Debug('Current Date'+dt);
    	for(string strObjectName : lstsObjectName) {
        for(sObject objsObject : database.query('Select Id,CreatedDate from ' + strObjectName+' Where CreatedDate <: dt')) {
          //  if(lstDeleteRecords.size() < 9998)
                lstDeleteRecords.add(objsObject);
           /* else {
                bReRun = true;
                break;
            }*/
        }
    }
    system.debug('Deleted Records'+lstDeleteRecords.size());
    }
    AccountSeedDataResponse wrapper = (AccountSeedDataResponse)JSON.deserialize(JsonResponse, AccountSeedDataResponse.class);
    
      for(AccountSeedDataResponse.Item_Z Itm_z : wrapper.PV_FIELD_TO_ACC_SEQ.Item)
    {
        Seeddata_Acc_Seq_fields__c Acc_Seq_Fields = new Seeddata_Acc_Seq_fields__c();
        Acc_Seq_Fields.AccountSequenceDescription__c =  Itm_z.ACC_SEQ_DESCR;
        Acc_Seq_Fields.AccountSequenceName__c =  Itm_z.ACC_SEQ_NAME;
		Acc_Seq_Fields.KEYFIELDNAME__c =  Itm_z.KEY_FIELDNAME;
        insertRecords.add(Acc_Seq_Fields);
    }
    
    for(AccountSeedDataResponse.Item Itm : wrapper.PV_ACC_SEQ_DATA.Item)
    {
          	Seeddata_Acc_Seq_Data__c Acc_Seq_Data = new Seeddata_Acc_Seq_Data__c();
            Acc_Seq_Data.AccountSequenceData__c =  Itm.ACC_SEQ_DATA;
            Acc_Seq_Data.AccountSequenceName__c =  Itm.ACC_SEQ_NAME;
        	insertRecords.add(Acc_Seq_Data);
    }
    
     for(AccountSeedDataResponse.Item_Y Itm_y : wrapper.PV_KEY_VALUES.Item)
    {
       
        SeeddataKeyValues__c PV_KEY_VALUES = new SeeddataKeyValues__c();
        PV_KEY_VALUES.FieldDescription__c =  Itm_y.FIELDDESCR;
        PV_KEY_VALUES.FieldName__c =  Itm_y.FIELDNAME;
        PV_KEY_VALUES.FieldValue__c = Itm_y.FIELDVALUE; 
        insertRecords.add(PV_KEY_VALUES);
    }

   
    system.debug('Inserted Records'+insertRecords.size());
   
    if(insertRecords.size()>0)
        insert insertRecords;
    
        if(lstDeleteRecords.size()>0)
        delete lstDeleteRecords;
}
global void finish(Database.BatchableContext ctx) {
    system.debug('batch finished');
 //   if(bReRun) {
//         Database.executebatch(new DeleteRecords());
    }
}