SM-Dev/src/objects/Seeddata_Acc_Seq_Data__c.object
<CustomObject>
    <description>This object holds the Account sequence Name and Account Sequence Data values structure of the Seed data provided by SAP.</description>
    <fields>
        <fullName>AccountSequenceData__c</fullName>
        <description>Account sequence data : This fields holds the Account sequence data value of the Account sequence data derived from the SAP seed data.</description>
        <label>Account Sequence Data</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountSequenceName__c</fullName>
        <description>Account sequence name : This fields holds the account sequence name of the Account sequence data derived from the SAP seed data.</description>
        <label>Account Sequence Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Seeddata_Acc_Seq_Data</label>
    <nameField>
        <displayFormat>SEQD-{0000}</displayFormat>
        <label>Account Sequence Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seeddata_Acc_Seq_Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SM-Dev/src/objects/Seeddata_Acc_Seq_fields__c.object
<CustomObject>
    <description>FIELD to account sequence : This object accommodates the field to account sequence mapping, which is derived from the SAP seed data service. This mapping is used to identify the dependency field values in the service.</description>
    <fields>
        <fullName>AccountSequenceDescription__c</fullName>
        <description>Account Sequence Description : This field accommodates the actual sequence description which tells us where to look into for the dependent field information. This data is derived from the SAP seed data.</description>
        <label>Account Sequence Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountSequenceName__c</fullName>
        <description>Account sequence name : This field accommodates the Account sequence name, which tells us the sequence Name to look into for the required information. This values is derived from the SAP system.</description>
        <label>Account Sequence Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KEYFIELDNAME__c</fullName>
        <description>KEY FIELD NAME : This Field accommodates the Values of the field we are looking for in the mapping structure. This data is derived from the SAP seed data service.</description>
        <label>KEY FIELD NAME</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Seeddata_Acc_Seq_Fields</label>
    <nameField>
        <displayFormat>SEQF-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seeddata_Acc_Seq_Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SM-Dev/src/objects/SeeddataKeyValues__c.object
<CustomObject>
    <description>Seeddata Key Values : This object accommodates the actually information and the description for individual seed data information. Actually raw data format.</description>
    <fields>
        <fullName>FieldDescription__c</fullName>
        <description>Field Description : This field accommodates the data description for the individual seed data values derived from the service.</description>
        <label>Field Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>FIELD NAME : This Field accommodates the Seed data type for the Raw data, this information is derived from the SAP system.</description>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldValue__c</fullName>
        <description>FIELD VALUE : This field accommodates the value of the individual seed data item. This is derived from the SAP seed data information.</description>
        <label>Field Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Seeddata_Key_Values</label>
    <nameField>
        <displayFormat>SDKEYVAL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seeddata_Key_values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SM-Dev/src/classes/SeedDataProcessorApex.cls
public with sharing class SeedDataProcessorApex {
	
    // This list has the data from SeeddataKeyValues__c Object, 3rd object data from seedData JSON structure. (Actuall Raw Data)
    public static List<SeeddataKeyValues__c> seedDataKeyValuesList = new List<SeeddataKeyValues__c>();  
    // This map has the the Key value pairs from the SeeddataKeyValues__c Object with fieldname__c as key and list<SeeddataKeyValues__c> related to that Fieldname as values. 3rd object data from seedData JSON structure.
    Public static map<string, list<SeeddataKeyValues__c>> seedDataKeyValuesMap = new map<string,list<SeeddataKeyValues__c>>();
    // This map has the the Key value pairs from the SeeddataKeyValues__c Object with fieldname__c+FieldValue__c as key and SeeddataKeyValues__c record related to that Fieldname+FieldValue as values. 3rd object data from seedData JSON
    Public static map<string, SeeddataKeyValues__c> seedDataKeyFieldValuesMap = new map<string,SeeddataKeyValues__c>();
    // This list has the data from Seeddata_Acc_Seq_Data__c object, 1st object from the Seed Data JSON structure. (Sequence Name and sequence Values to be looked into for actuall pattern)
    public static List<Seeddata_Acc_Seq_Data__c> seedDataAccSeqDataList = new List<Seeddata_Acc_Seq_Data__c>();
    // This Map has the Key value pairs from the Seeddata_Acc_Seq_Data__c with AccountSequenceName__c as Key and List<AccountSequenceData__c> related to the AccountSequenceName__c as Values.
    Public static map<string, list<string>> seedDataAccSeqDataMap = new map<string,list<string>>();
    // This List has the data from the Seeddata_Acc_Seq_fields__c object, 2nd object from the SeedData JSON service. (Data pattern Mapping structure).
    public static List<Seeddata_Acc_Seq_fields__c> seedDataAccSeqFieldsList = new List<Seeddata_Acc_Seq_fields__c>();  
    // This Map has the data from the Seeddata_Acc_Seq_fields__c with KEYFIELDNAME__c as a Key and AccountSequenceName__c as a Value,(This is to tell us that for a required field which Account sequence data we need to look into from the 1st table of Seed Data JSON).
    Public static map<string,string> seedDataAccSeqFieldsMap = new map<string,string>();
    // This Map has the data from the Seeddata_Acc_Seq_fields__c with the KEYFIELDNAME__c as Key and its position in the dependency structure, which is the AccountSequenceDescription__c, (This tells us which part of the Account sequence data to look into for the actuall data from the 1st object of JSON-Seeddata_Acc_Seq_Data__c)
    Public static map<string, Integer> SeedDataFieldNamePositionMap = new map<string,Integer>();
    
    @AuraEnabled
    public static SeedDataWrapper getRawSeedData()
    {
        
        seedDataKeyValuesList = [SELECT Id,FieldName__c,FieldValue__c,FieldDescription__c FROM SeeddataKeyValues__c];
        seedDataAccSeqDataList = [SELECT Id,AccountSequenceData__c,AccountSequenceName__c FROM Seeddata_Acc_Seq_Data__c  ];
        seedDataAccSeqFieldsList = [SELECT Id,KEYFIELDNAME__c,AccountSequenceName__c,AccountSequenceDescription__c FROM Seeddata_Acc_Seq_fields__c];
        if(seedDataKeyValuesList.size()>0)
        {
            for(SeeddataKeyValues__c SDKV : seedDataKeyValuesList)
            {
                if(seedDataKeyValuesMap.containsKey(SDKV.FieldName__c))
                {seedDataKeyValuesMap.get(SDKV.FieldName__c).add(SDKV);}
                 else
                { seedDataKeyValuesMap.put(SDKV.FieldName__c, new list<SeeddataKeyValues__c>{SDKV});}
                
                seedDataKeyFieldValuesMap.put(SDKV.FieldName__c+SDKV.FieldValue__c, SDKV);
                
            }
        }
        system.debug('Test for map 1-->'+seedDataKeyFieldValuesMap);
        if(seedDataAccSeqDataList.size()>0)
        {
            for(Seeddata_Acc_Seq_Data__c SDASD : seedDataAccSeqDataList)
            {
                if(seedDataAccSeqDataMap.containsKey(SDASD.AccountSequenceName__c))
        {seedDataAccSeqDataMap.get(SDASD.AccountSequenceName__c).add(SDASD.AccountSequenceData__c);}
         else
         { seedDataAccSeqDataMap.put(SDASD.AccountSequenceName__c, new List<string>{SDASD.AccountSequenceData__c});}
            }
        }
        if(seedDataAccSeqFieldsList.size()>0)
        {
            for(Seeddata_Acc_Seq_fields__c SDASF : seedDataAccSeqFieldsList)
            {
                seedDataAccSeqFieldsMap.put(SDASF.KEYFIELDNAME__c,SDASF.AccountSequenceName__c);
                if(SDASF.KEYFIELDNAME__c == 'SALES_OFFICE' || SDASF.KEYFIELDNAME__c == 'SALES_GROUP' || SDASF.KEYFIELDNAME__c == 'PLANT')
                {
                    String seedDataDesc = SDASF.AccountSequenceDescription__c;
                    String[] seedDataDescArray = seedDataDesc.split('-');
                    for(String s : seedDataDescArray)
                       {
                           SeedDataFieldNamePositionMap.put(s,seedDataDescArray.Indexof(s));
                       }
                    system.debug('pos-->'+SeedDataFieldNamePositionMap);
                }
            }
        }
        system.debug('Test for object'+SeedDataFieldNamePositionMap);
        SeedDataWrapper dataWrapper = new SeedDataWrapper();
        dataWrapper.seedDataKeyValuesMap_wrapper = seedDataKeyValuesMap;
        dataWrapper.seedDataKeyFieldValuesMap_wrapper = seedDataKeyFieldValuesMap;
        dataWrapper.seedDataAccSeqDataMap_wrapper = seedDataAccSeqDataMap;
        dataWrapper.seedDataAccSeqFieldsMap_wrapper = seedDataAccSeqFieldsMap;
        dataWrapper.SeedDataFieldNamePositionMap_wrapper = SeedDataFieldNamePositionMap;
        return dataWrapper;
    }
    
    public class SeedDataWrapper{
       
        @AuraEnabled Public map<string, list<SeeddataKeyValues__c>> seedDataKeyValuesMap_wrapper {get;set;}
        @AuraEnabled Public  map<string, SeeddataKeyValues__c> seedDataKeyFieldValuesMap_wrapper {get;set;}
        @AuraEnabled Public map<string, list<string>> seedDataAccSeqDataMap_wrapper {get;set;}     
        @AuraEnabled Public map<string,string> seedDataAccSeqFieldsMap_wrapper {get;set;}     
        @AuraEnabled Public map<string, Integer> SeedDataFieldNamePositionMap_wrapper {get;set;}

    }
}